### ISSUE TITLE
Java module does not work on windows system. (python module works a bit better) 

### ISSUE THREAD

**Issue by vsilent** [Plug-up/daplug-java#2]
Hello, we have problem with start modules on windows. 

OS: Windows 7 x86
USB drivers: WinUSB, libusbK, libusb-win32

When calling getFirstDongle() of DaplugSession object 
we get an exception java.lang.IllegalArgumentException: device must not 
be null
On Ubuntu x64 there is no exceptions, everything is working fine.

Here is an example of code that produces exception:

import io.daplug.session.DaplugSession;
import io.daplug.utils.DaplugUtils;

public class PlugUpTest {

```
 public static void main(String[] args) {
     String serial = null;
     DaplugSession daplugSession = new DaplugSession();

     try{
         daplugSession.getDonglesList();
         daplugSession.getFirstDongle();
         serial = 
```

DaplugUtils.byteArrayToHexString(daplugSession.getDongleSerial());
         }catch (Exception ex){
             System.out.println(ex.toString());
         }

```
     System.out.println(serial);
     System.exit(0);
 }
```

}

Can you look into this ? 

Note that Python version works a bit better, at least it gives me a serial key of the device but gets frozen after printing it.
Thanks

**Comment by benamsaap** [comment]
Hello,

Have you added the external JARs to your classpath?
- usb4java (http://usb4java.org/index.html).
- javahidapi (https://code.google.com/p/javahidapi/).

They should already be included in the project (daplug-java/libs).

**Comment by vsilent** [comment]
Yes, otherwise we could not compile it.

**Comment by benamsaap** [comment]
Of course.. Sorry..
Try to install usb driver using zadig (http://zadig.akeo.ie/).

**Comment by vsilent** [comment]
Drivers are installed ok. Devices detected, but daplug-java application gives an exception. We were able to connect and read device using libusb standard library for java and it worked well.

**Comment by benamsaap** [comment]
What kind of token do you have?

**Comment by vsilent** [comment]
If you mean the device, we use plug-up  like this one http://marketing.plug-up.com/

**Comment by benamsaap** [comment]
I just tested your code on Windows 7 x86 with no problems ..
I recommend you to reinstall drivers using zadig..

**Comment by vsilent** [comment]
nope, does not works for win 8 too. We tryed all drivers but no success. Which driver are you using in your tests ?

**Comment by vsilent** [comment]
Ok we got it. It works when we switch to HID mode. Try to switch to winUSB mode.

**Comment by benamsaap** [comment]
The API isn't tested on Windows 8.
I use the WinUSB driver (v6.1.7600.16385), installed using zadig.

**Comment by benamsaap** [comment]
Yes, there is two modes : winusb and hid ; it should work for the two.

**Comment by vsilent** [comment]
When we switch to winUSB mode programmatic-ally we get errors. I think if you try to switch you will get it.

**Comment by benamsaap** [comment]
Do you mean when you try to switch or when you use the device in WINUSB mode?
Have you tried to reinstall driver using zadig?
What are the message error detail?

**Comment by vsilent** [comment]
Do you mean when you try to switch or when you use the device in WINUSB mode? - When device is in WINUSB mode.
Have you tried to re-install driver using zadig?  -  Yes, we tried all versions of drivers
What are the message error detail?   -  "device must not 
be null".

**Comment by benamsaap** [comment]
if you use only daplugSession.getDonglesList(), do you get errors?

**Comment by vsilent** [comment]
daplugSession.getDonglesList() does not give errors. Exception raised on  getFirstDongle()
I attach a screenshot 
![untitled](https://cloud.githubusercontent.com/assets/42473/6369542/1ea1f7aa-bcf0-11e4-872d-9706bed8b0f7.png)

**Comment by vsilent** [comment]
Were you able to reproduce this problem ? Should I present more information for this bug ?

**Comment by benamsaap** [comment]
Sorry for the delay.. I'll see it ASAP.

**Comment by benamsaap** [comment]
Bug fixed.. Thank you for reporting..
