### ISSUE TITLE
Each call of getDonglesList() increments the list of devices

### ISSUE THREAD

**Issue by vsilent** [Plug-up/daplug-java#4]
package com.oweb.plugup_auth.etc;
import io.daplug.session.DaplugSession;

public class PlugUpTest {

```
public static void main(String[] args) {
    DaplugSession daplugSession = new DaplugSession();
    try{

        daplugSession.getDonglesList(); System.out.print("\n");
        daplugSession.getDonglesList(); System.out.print("\n");
        daplugSession.getDonglesList(); System.out.print("\n");
        daplugSession.getDonglesList(); System.out.print("\n");

    }catch (Exception ex){
        System.out.println(ex.getMessage());
    }
}
```

}

output:
List all Daplug Dongle (HID/WINUSB)
Dongle 0,WINUSB,1682535504,Plug-up

List all Daplug Dongle (HID/WINUSB)
Dongle 0,WINUSB,1682535504,Plug-up
Dongle 0,WINUSB,1682657464,Plug-up

List all Daplug Dongle (HID/WINUSB)
Dongle 0,WINUSB,1682535504,Plug-up
Dongle 0,WINUSB,1682657464,Plug-up
Dongle 0,WINUSB,1682664056,Plug-up

List all Daplug Dongle (HID/WINUSB)
Dongle 0,WINUSB,1682535504,Plug-up
Dongle 0,WINUSB,1682657464,Plug-up
Dongle 0,WINUSB,1682664056,Plug-up
Dongle 0,WINUSB,1682669360,Plug-up

description:
Each call of getDonglesList() appends a device to the list of device handlers.
But we have only one device plugged in. Please check it.

**Comment by benamsaap** [comment]
Bug fixed..
Thank you for reporting..
